version: "{branch}-ci-{build}"
image: Visual Studio 2019

build: msvc
platform: x86
configuration: Debug

install:
- choco install opencppcoverage codecov
- set PATH=C:\Program Files\OpenCppCoverage;%PATH%

build_script:
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake ..
- cd ..
- cmake --build .\build\ --config Debug
- OpenCppCoverage.exe --export_type=cobertura:cobertura.xml --stop_on_assert --sources ExcaliburHashTest*.* --sources ExcaliburHash.h --excluded_sources *googletest* --modules *.exe -- .\build\Debug\ExcaliburHashTest.exe
- codecov -f cobertura.xml --root %APPVEYOR_BUILD_FOLDER% -t 6ff3ea6c-1bf4-47b4-b046-bd204afef71f
